# This is a basic workflow to help you get started with Actions

name: Build Eleventy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1

    - name: Start docker image
      run: docker run --publish 8080:8080 --detach ghcr.io/eeditiones/tei-guidelines/teiguidelines:master

    - name: Wait for eXist
      uses: iFaxity/wait-on-action@v1
      with:
        resource: http-get://localhost:8080/exist/apps/guidelines/index.html

    - name: Install packages
      run: npm ci

    - name: Run npm build
      run: npm run build.all

    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: deploy # The branch name where you want to push the assets
        FOLDER: ./_site # The directory where your assets are generated
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "Build: ({sha}) {msg}" # The commit message